name: referal-API-compose

volumes:
  postgres_data:

networks:
  main_network:

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_container
    env_file:
      - .env
    healthcheck:
      test: "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      interval: 3s
      timeout: 7s
      retries: 6
    ports:
      - "5432:5432"                                  # port exposed for dbeaver
    restart: unless-stopped
    networks:
      - main_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  fastapi_app:
    build:
      context: ./app
      additional_contexts:
        - root=./
    container_name: fastapi_container
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - main_network